# Generated by Django 3.1.3 on 2020-12-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadcalender',
            name='geeks_field',
        ),
        migrations.AddField(
            model_name='uploadcalender',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadcalender',
            name='img',
            field=models.ImageField(default='', upload_to='static/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadcalender',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default='2020-12-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadcalender',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
