# Generated by Django 3.1.3 on 2020-12-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20201201_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcalender',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadcalender',
            name='img',
            field=models.ImageField(default='', upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='uploadcalender',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
