# Generated by Django 3.1.3 on 2020-12-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_uploadcalender_img2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadcalender',
            name='img2',
        ),
        migrations.AlterField(
            model_name='uploadcalender',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadcalender',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
