# Generated by Django 3.1.3 on 2020-12-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_auto_20201201_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('tt_img', models.ImageField(default='', upload_to='static/images/')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadcalender',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadcalender',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
