# Generated by Django 3.1.3 on 2020-12-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_auto_20201202_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.CharField(blank=True, default='', max_length=100)),
                ('pdf', models.FileField(default='', upload_to='static/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='SemII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.CharField(blank=True, default='', max_length=100)),
                ('pdf', models.FileField(default='', upload_to='static/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='SemIII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.CharField(blank=True, default='', max_length=100)),
                ('pdf', models.FileField(default='', upload_to='static/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='SemIV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.CharField(blank=True, default='', max_length=100)),
                ('pdf', models.FileField(default='', upload_to='static/pdfs/')),
            ],
        ),
    ]
