# Generated by Django 3.1.3 on 2020-12-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_semi_semii_semiii_semiv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SemI',
            new_name='SemFour',
        ),
        migrations.RenameModel(
            old_name='SemII',
            new_name='SemOne',
        ),
        migrations.RenameModel(
            old_name='SemIV',
            new_name='SemThree',
        ),
        migrations.RenameModel(
            old_name='SemIII',
            new_name='SemTwo',
        ),
    ]
