# Generated by Django 3.1.3 on 2020-12-03 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_auto_20201202_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SemFour',
        ),
        migrations.DeleteModel(
            name='SemOne',
        ),
        migrations.DeleteModel(
            name='SemThree',
        ),
        migrations.DeleteModel(
            name='SemTwo',
        ),
    ]
