# Generated by Django 3.1.3 on 2020-12-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_semone'),
    ]

    operations = [
        migrations.AddField(
            model_name='semone',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='semone',
            name='pdf_f',
            field=models.FileField(blank=True, default='', upload_to='static/pdfs/'),
        ),
    ]
