# Generated by Django 3.1.3 on 2020-12-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_semtwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemEight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.CharField(blank=True, default='', max_length=100)),
                ('pdf_f', models.FileField(blank=True, default='', upload_to='static/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='SemFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.CharField(blank=True, default='', max_length=100)),
                ('pdf_f', models.FileField(blank=True, default='', upload_to='static/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='SemFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.CharField(blank=True, default='', max_length=100)),
                ('pdf_f', models.FileField(blank=True, default='', upload_to='static/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='SemSeven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.CharField(blank=True, default='', max_length=100)),
                ('pdf_f', models.FileField(blank=True, default='', upload_to='static/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='SemSix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.CharField(blank=True, default='', max_length=100)),
                ('pdf_f', models.FileField(blank=True, default='', upload_to='static/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='SemThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.CharField(blank=True, default='', max_length=100)),
                ('pdf_f', models.FileField(blank=True, default='', upload_to='static/pdfs/')),
            ],
        ),
    ]
